steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  args:
    - -c
    - './make_secret.sh && app deploy app.yaml --project=library-checker-project'
  env:
    - 'PG_HOST=$_PG_HOST'
    - 'PG_PASS=$_PG_PASS'
    - 'SESSION_SECRET=$_SESSION_SECRET'

timeout: 1800s
